---
logging.level.org.hibernate.SQL: debug
spring.jpa.properties.hibernate.hbm2ddl.auto: validate
spring.datasource.initialize: true
spring.datasource.data: classpath*:data-from-migration.sql,classpath*:data.sql,classpath*:data-gen.sql,classpath*:data-personas.sql
